import Card from "@/components/Card";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="grid grid-cols-[repeat(auto-fill,minmax(220px,1fr))] p-2 gap-x-2 gap-y-24 overflow-hidden">
          {Array(24)
            .fill(0)
            .map((_, i) => (
              <Card key={i} />
            ))}
        </div>
      </main>
    </>
  );
}
